### ISSUE TITLE
Repo Feedback

### ISSUE THREAD

**Issue by TomHAnderson** [basz/zf-oauth2-doctrine-mutatetablenames#1]
I like what you've done.  However your namespace is wrong.  I'd like to see it as ZF\OAuth2\Doctrine\MutableTableNames.  This is an inconsistency since even the repo name suggests this namespace.  

I like having this and zf-oauth2-doctrine in different repos too, for now, but if your module becomes popular I think we should consider including it with zf-oauth2-doctrine because popularity would indicate necessity.  However if we were to merge them we could have a separate config for table names and a flag like 'enable_default_entities' => true, ... 'enable_mutable_tablenames' => true  I'd like your ideas here.

The modules in zfcampus all keep their Module.php in the repo root dir e.g. https://github.com/zfcampus/zf-rest/blob/master/Module.php  I understand the idea of linking the module under the namespace but composer accounts for this:  https://github.com/zfcampus/zf-rest/blob/master/composer.json#L58

**Comment by basz** [comment]
think it is done : min having a quick second review? https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/commit/228fcfa4c12edf29b664fd260d276a35f51f85d9
