### ISSUE TITLE
Update to support latest zf-oauth2-doctrine config 

### ISSUE THREAD

**Issue by TomHAnderson** [basz/zf-oauth2-doctrine-mutatetablenames#14]
Multiple OAuth2 instances are supported by zf-oauth2-doctrine.  This module needs to be updated to support them.  I'll need to remove this from the suggest in composer if this isn't updated.

**Comment by basz** [comment]
Hi

Sure ill have look soon. I dont use this packagemaker myself anymore so a bit out of the loop :)

**Comment by basz** [comment]
Hi Tom, are you able to quickly review and/or test https://github.com/basz/zf-oauth2-doctrine-mutatetablenames/pull/17 ? This should add support for multiple OAuth services, but I playing blind here :-)

ps. I've modernised it also to work with sm3 and added tests.

**Comment by basz** [comment]
just released 0.4 with adds the requested support
