### ISSUE TITLE
Update to support latest zf-oauth2-doctrine 2.0

### ISSUE THREAD

**Issue by brndusic** [basz/zf-oauth2-doctrine-mutatetablenames#19]
Hi please update your composer.json to support zf-oauth2-doctrine 2.0 and later. Major version is released and now requirements could not be resolved to an installable set of packages.

**Comment by basz** [comment]
I'm not sure it'll work with v2. I'm not using this myself anymore, but if you can make a PR I'll be willing to merge...

**Comment by sergiohermes** [comment]
Hello u can create release for this update?

```
Problem 1
    - Installation request for bushbaby/zf-oauth2-doctrine-mutatetablenames ^0.4.0 -> satisfiable by bushbaby/zf-oauth2-doctrine-mutatetablenames[0.4.0].
    - bushbaby/zf-oauth2-doctrine-mutatetablenames 0.4.0 requires api-skeletons/zf-oauth2-doctrine ^1.0 -> satisfiable by api-skeletons/zf-oauth2-doctrine[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2] but these conflict with your requirements or minimum-stability.

```
ty. :D :neckbeard:

**Comment by basz** [comment]
Done, you’ll need to update the composer.json to require 0.5

Thanks
