### ISSUE TITLE
Release 0.2.0 is broken

### ISSUE THREAD

**Issue by waltertamboer** [basz/zf-oauth2-doctrine-mutatetablenames#3]
There are syntax errors in oauth2.doctrine-orm.mutatetablenames.global.php.dist

**Comment by basz** [comment]
Ill do a 0.2.1 of master soon. Ping me of i didnt do this over the weekend.

**Comment by basz** [comment]
done, let me know if you find more issues. thanks

**Comment by waltertamboer** [comment]
Cheers Bas. Thanks for the quick response.
