### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by waltertamboer** [basz/zf-oauth2-doctrine-mutatetablenames#4]
How does one properly setup this module? It looks like a big part of the documentation is missing.

For example, the predefined tables such as `oauth2_accesstoken` are not configured in such a way that Apigility knows about them. This results in an error: `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.oauth_clients' doesn't exist`
This should be fixed by either changing the table name or by adding a `storage_settings` section to:
```php
<?php
return array(
    'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'myadapter' => array(
                    // ...
                    'storage' => array(
                        // ...
                        'storage_settings' => array(
                            'client_table' => 'oauth2_client',
                        ),
                    ),
                ),
            ),
        ),
    ),
);
```

This results in another error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'client_id' in 'where clause'` This is because the column is called `clientId` in my database.

Help! :)

**Comment by basz** [comment]
Hi Walter,

This module augments https://github.com/TomHAnderson/zf-oauth2-doctrine such that you can use different table names for the tables that module provides.

I recommend setting up that module first and use this one when zf-oauth2-doctrine is working as expected.

client_id vs clientId is not within the scope of this module - however I think it should be possible to change those column names by modifying the mapping information zf-oauth2-doctrine provides. (it's fairly complicated if you don't know exactly what your doing...)

**Comment by basz** [comment]
@waltertamboer did you solve your issues?

**Comment by waltertamboer** [comment]
Hi Bas, yes it's solved.
