### ISSUE TITLE
Conflict after were merged feature/zf-mvc-auth in zf-oauth2-doctrine

### ISSUE THREAD

**Issue by viniciusgava** [basz/zf-oauth2-doctrine-mutatetablenames#5]
Hey there,
I am testing the zf-oauth2-doctrine after were merged the feature/zf-mvc-auth feature and I think it is necessary some adjust for work with multiple oauth now.

**Comment by basz** [comment]
@TomHAnderson are you able to confirm this? Could you quickly express the global changes needed. I've been out of touch on this project for a while...

**Comment by TomHAnderson** [comment]
The `/config/oauth2.doctrine-orm.global.php.dist` is now keyed for multiple OAuth2 services.  The 'default' is now provided.

I think this needs to be changed to support mulitple profiles
```php
return array(
    'zf-oauth2-doctrine' => array(
        'mutatetablenames' => array(
            'multiple-profile-key-eg-default' => array(
```

Then loop on mutatetablenames and rename entities in each profile.
