### ISSUE TITLE
Configuration of name of configuration

### ISSUE THREAD

**Issue by hlogeon** [basz/zf-oauth2-doctrine-mutatetablenames#7]
I have been trying to implement zf-oauth2-doctrine and zf-oauth2-doctrine-mutatetablenames
but when it's came to use it I found out that "zf-oauth2-doctrine-mutatetablenames" module expects 'zf-oauth2-doctrine' config to have "storage_settings" key with exactly same data as in "default" section in zf-oauth2-doctrine. So, when I change "default" to required, zf-oauth2-doctrine shows me error that the key "default" doesn't exists. Of course, I can have both keys, bu it's not a good way to solve this problem. Could you tell me what am I doing wrong?

**Comment by basz** [comment]
I think 0.2.2 resolves your problems. please try again.
