### ISSUE TITLE
Abandoned composer repository

### ISSUE THREAD

**Issue by brndusic** [basz/zf-oauth2-doctrine-mutatetablenames#8]
In composer file there is abandoned zfcampus/zf-oauth2-doctrine reference.
You should use this one api-skeletons/zf-oauth2-doctrine

Here is warning from composer:
- Package zfcampus/zf-oauth2-doctrine is abandoned, you should avoid using it. Use api-skeletons/zf-oauth2-doctrine instead.

**Comment by basz** [comment]
Thx. Several repos need some love. Ill het to it soon
